---
title: Shakespeare-beledigingsgenerator
hero_image: images/banner.png
description: In deze bron zul je een Python-script schrijven om beledigingen te genereren, in Elizabethaanse stijl.
original_url: https://raspberrypi.org/learning/shakespearean-insult-generator
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-0, manufacture-0, community-0
interests: literature
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2018-04-05
steps:
  - 
    title: Inleiding
  - 
    title: Open and read from a file
    completion:
      - engaged
  - 
    title: Lists in Python
  - 
    title: Randomly choosing an insult
    completion:
      - internal
  - 
    title: What can you do now?
    completion:
      - external
