---
title: Shakespearean insult generator
hero_image: images/banner.png
description: In this resource you will write a Python script to generate insults, Elizabethan-style.
original_url: https://raspberrypi.org/learning/shakespearean-insult-generator
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-0, manufacture-0, community-0
interests: literature
technologies: raspberry-pi, python
site_areas: projects
hardware: raspberry-pi
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Shakespearean insult generator
- title: What is a CSV file?
- title: Putting your insults into a CSV file
- title: Open and read from a file
- title: Lists in Python
- title: Randomly choosing an insult
- title: Displaying the result on a GUI
- title: What next
