---
title: शेक्सपियरेन अपमान उत्पादक
hero_image: images/banner.png
description: इस संसाधन में आप अपमान उत्पन्न करने के लिए Python स्क्रिप्ट लिखेंगे, एलिज़ाबेथन-शैली में।
original_url: https://raspberrypi.org/learning/shakespearean-insult-generator
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-0, manufacture-0, community-0
interests: साहित्य
technologies: python
site_areas: परियोजनाएं
hardware: ''
software: python
version: 3
last_tested: 2018-04-05
steps:
  - 
    title: भूमिका
  - 
    title: आपको किन चीज़ों की आवश्यकता होगी
  - 
    title: शेक्सपियरेन अपमान उत्पादक
  - 
    title: CSV फ़ाइल क्या है?
  - 
    title: अपने अपमानों को एक CSV फ़ाइल में डालना
  - 
    title: एक फाइल को खोलें और पढ़ें
  - 
    title: Python में सूचियाँ
  - 
    title: निरुद्देश्यता से अपमान चुनना
  - 
    title: GUI पर परिणाम प्रदर्शित करना
  - 
    title: आगे क्या
